wandb_version: 1

algorithm_name:
  desc: null
  value: mappo
experiment_name:
  desc: null
  value: SMAC-LOAD4m_vs_5m-TrainSI-MAPPO-Steps50M-50M
seed:
  desc: null
  value: 3
cuda:
  desc: null
  value: false
cuda_deterministic:
  desc: null
  value: true
n_training_threads:
  desc: null
  value: 1
n_rollout_threads:
  desc: null
  value: 8
n_eval_rollout_threads:
  desc: null
  value: 1
n_render_rollout_threads:
  desc: null
  value: 1
num_env_steps:
  desc: null
  value: 50000000
user_name:
  desc: null
  value: marl
use_wandb:
  desc: null
  value: true
env_name:
  desc: null
  value: StarCraft2
use_obs_instead_of_state:
  desc: null
  value: false
episode_length:
  desc: null
  value: 400
share_policy:
  desc: null
  value: true
use_centralized_V:
  desc: null
  value: true
stacked_frames:
  desc: null
  value: 1
use_stacked_frames:
  desc: null
  value: false
hidden_size:
  desc: null
  value: 64
layer_N:
  desc: null
  value: 1
use_ReLU:
  desc: null
  value: true
use_popart:
  desc: null
  value: false
use_valuenorm:
  desc: null
  value: true
use_feature_normalization:
  desc: null
  value: true
use_orthogonal:
  desc: null
  value: true
gain:
  desc: null
  value: 0.01
use_naive_recurrent_policy:
  desc: null
  value: false
use_recurrent_policy:
  desc: null
  value: false
recurrent_N:
  desc: null
  value: 1
data_chunk_length:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0005
critic_lr:
  desc: null
  value: 0.0005
opti_eps:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0
kl_threshold:
  desc: null
  value: 0.01
ls_step:
  desc: null
  value: 10
accept_ratio:
  desc: null
  value: 0.5
ppo_epoch:
  desc: null
  value: 10
use_clipped_value_loss:
  desc: null
  value: true
clip_param:
  desc: null
  value: 0.05
num_mini_batch:
  desc: null
  value: 1
entropy_coef:
  desc: null
  value: 0.01
value_loss_coef:
  desc: null
  value: 1
use_max_grad_norm:
  desc: null
  value: true
max_grad_norm:
  desc: null
  value: 10.0
use_gae:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
use_proper_time_limits:
  desc: null
  value: false
use_huber_loss:
  desc: null
  value: true
use_value_active_masks:
  desc: null
  value: false
use_policy_active_masks:
  desc: null
  value: true
huber_delta:
  desc: null
  value: 10.0
use_linear_lr_decay:
  desc: null
  value: false
save_interval:
  desc: null
  value: 1
log_interval:
  desc: null
  value: 5
use_eval:
  desc: null
  value: true
eval_interval:
  desc: null
  value: 100
eval_episodes:
  desc: null
  value: 32
save_gifs:
  desc: null
  value: false
use_render:
  desc: null
  value: false
render_episodes:
  desc: null
  value: 5
ifi:
  desc: null
  value: 0.1
model_dir:
  desc: null
  value: ../../official_saved_models/4m_vs_5m/SMAC-4m_vs_5m-MAPPO-SuperLong50M(Seed3_Run1_Ser1)/Policy_Episode50.0M
no_train_policy:
  desc: null
  value: true
encode_state:
  desc: null
  value: false
n_block:
  desc: null
  value: 1
n_embd:
  desc: null
  value: 64
n_head:
  desc: null
  value: 1
dec_actor:
  desc: null
  value: false
share_actor:
  desc: null
  value: false
train_maps:
  desc: null
  value: null
eval_maps:
  desc: null
  value: null
evaluate_two_social_influence:
  desc: null
  value: false
model_dir_si_learning:
  desc: null
  value: null
model_dir_si_fixed:
  desc: null
  value: null
only_use_argmax_policy:
  desc: null
  value: false
only_use_argmax_action:
  desc: null
  value: true
minimal_gifs:
  desc: null
  value: true
no_train_si:
  desc: null
  value: false
si_loss_type:
  desc: null
  value: kl
policy_model_dir_teamA:
  desc: null
  value: null
policy_model_dir_teamB:
  desc: null
  value: null
si_model_dir_teamA:
  desc: null
  value: null
si_model_dir_teamB:
  desc: null
  value: null
run_mixed_population:
  desc: null
  value: false
map_name:
  desc: null
  value: 4m_vs_5m
units:
  desc: null
  value: 10v10
add_move_state:
  desc: null
  value: false
add_local_obs:
  desc: null
  value: false
add_distance_state:
  desc: null
  value: false
add_enemy_action_state:
  desc: null
  value: false
add_agent_id:
  desc: null
  value: false
add_visible_state:
  desc: null
  value: false
add_xy_state:
  desc: null
  value: false
use_state_agent:
  desc: null
  value: true
use_mustalive:
  desc: null
  value: true
add_center_xy:
  desc: null
  value: true
grp_social_influence:
  desc: null
  value: false
teamB_map_name:
  desc: null
  value: 4m
use_group_social_influence:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.6.1
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725067833.543703
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.6.1
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
